name: hyun-deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to HyunActions
        uses: Hyunsu-Playground/Hyun-Action@main
        with:
          environment: stag
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}